### PR TITLE
Support nullable custom type

### PR DESCRIPTION
**Pull request by wangrzneu**
Fixes Or Enhances # .

**Make sure that you've checked the boxes below before you submit PR:**
- [x] Tests exist or have been written that cover this particular change.

Change Details:

- Support nullable custom type

@go-playground/admins

### CODE REVIEW

**Comment by wangrzneu** [comment]
@deankarn PTAL

**Comment by deankarn** [comment]
@wangrzneu I'm wondering what does this gain us over https://github.com/go-playground/validator/blob/master/_examples/custom/main.go?

apologies if I'm missing something obvious, didn't get a lot of sleep last night.

**Comment by wangrzneu** [comment]
> @wangrzneu I'm wondering what does this gain us over https://github.com/go-playground/validator/blob/master/_examples/custom/main.go?
> 
> apologies if I'm missing something obvious, didn't get a lot of sleep last night.

This example outputs: 
```
Err(s):
Key: 'DbBackedUser.Name' Error:Field validation for 'Name' failed on the 'required' tag
Key: 'DbBackedUser.Age' Error:Field validation for 'Age' failed on the 'required' tag
```

I think field validation for 'Name'  should success, because Name.Valid is `true`.

**Comment by deankarn** [comment]
@wangrzneu in this case you can just the custom function to output a value that will pass validation. I just posted an example, you can change the function to suite your needs.

Going to close this PR, this conversation seems better served in  an issue.

**Pull request closed without merging**
