### PR TITLE
Add validation functions for tcp/udp/ip/unix addresses

### PR DESCRIPTION
**Pull request by krhubert**
What do you think of those fileds? If you think it's good idea I can create some docs + tests.

Why I think is good?
I constatly need to parse some bind addreses for other services (http, etc....) and would be nice to validate those adresses, not it time when service will be starded.

### CODE REVIEW

**Comment by joeybloggs** [comment]
This is awesome! Thanks @krhubert

So these validate that the address is resolvable not just a valid address I can see how this would be very useful.

I'd love for you to create some docs and tests!

**Comment by krhubert** [comment]
Ok, i think it's done, can you review it?
Also I found possible ambiguity in golang (https://github.com/golang/go/issues/14037). The tests are aware of it.

**Comment by joeybloggs** [comment]
Thanks I will review ASAP and if all is well merge this morning

**Comment by joeybloggs** [comment]
so working on it now, am trying to fix the issue you filed with go.

but I have a question, because you are probably more familiar with networking than I.

take net.ResolveUnixAddr should it not error out when trying to validate a blank string? see here https://play.golang.org/p/0To1JR2dE9

**Comment by krhubert** [comment]
Good question - I think it should :) but now i'm not 100% sure

https://play.golang.org/p/3UUNtI7Cig => here validation of empty tcp addres => this one I think it's ok, becouse it means 0.0.0.0:0, but it can be error prone.

I think you can leave it as it is, and maybe wait for some feedback. Also wait for go isssue to be solved

**Comment by joeybloggs** [comment]
ok I'm going to add a workaround for https://github.com/golang/go/issues/14037 as much as possible though, otherwise incorrect data may get saved in someones DB.

Here's what I have so far:
https://github.com/go-playground/validator/blob/krhubert/baked_in.go#L1254
https://github.com/go-playground/validator/blob/krhubert/baked_in.go#L1272
https://github.com/go-playground/validator/blob/krhubert/baked_in.go#L1323
https://github.com/go-playground/validator/blob/krhubert/baked_in.go#L1335
https://github.com/go-playground/validator/blob/krhubert/baked_in.go#L1347

that's all I've had time to do thus far, to accept "" just have to add to the if's as an example:
```go
if val != "" && !IsIPv4(v, topStruct, currentStructOrField, reflect.ValueOf(val), fieldType, fieldKind, param) {
```

I'll have to continue work on it later, or you can help finish them if you'd like.

Just can't have bad data pass is all.

**Comment by krhubert** [comment]
There is update on https://github.com/golang/go/issues/14037

**Comment by joeybloggs** [comment]
looks like there going to let the community come up with some idea's and have the fix slated for go1.7

I will keep implementing the workaround for now as best I can.

**Comment by joeybloggs** [comment]
Apologies for this taking so long @krhubert I will get it in as soon as I can..just have a few other projects eating all my time; should be this week though

**Comment by krhubert** [comment]
No problem, I was busy too, I should be avaiable on monday, then I can help you with this.

**Comment by joeybloggs** [comment]
Just an update, haven't forgotten about this, just still busy with another project... I will try my best to get it done this week any help would be welcome.

**Comment by krhubert** [comment]
Same for me ^^ :D, but I want to do this too!

**Comment by joeybloggs** [comment]
Hey @krhubert finally squeezed in some time to get this done! :smiley: 

I think I've covered all the basics, if could you could please take a look at this branch: https://github.com/go-playground/validator/tree/krhubert and run some tests on your end to ensure it works for you, I can get it merged in.

P.S. ResolveUnixAddr I was discussing with a network specialist and he said that a blank unix addr is valid as it's assumed to be 0.0.0.0 ... I'm taking him at his word on that and "" is still valid in the test.

**Comment by krhubert** [comment]
Hey, great :), Sorry but I still lack of time :/

For me everthing seems fine and good:

`[root@debian $GOPATH/src/github.com/go-playground/validator (krhubert)] go test
PASS
ok  	github.com/go-playground/validator	0.009s
`

I show your discussion about the UnixAddr, still I think it's strange.

**Comment by joeybloggs** [comment]
@krhubert  I will research a little bit more about UnixAddr, but even if it's left this way you can also add the "required" tag along with the "unix_addr" one and make it fail for blank that way.

I will get this merged in sometime tonight.

**Comment by joeybloggs** [comment]
@krhubert ok I'm going to close this and make a pull request from my krhubert branch as everything is in there already. just a point of interest but have you looked at the ResolveUnixAddr code, it doesn't do anything but ensure the net string is a valid unix type and then just returns a new UnixAddr object see here https://golang.org/src/net/unixsock.go?s=826:883#L30

**Comment by krhubert** [comment]
@joeybloggs yes I have seen UnixAddr, TcpAddr, UpdAddr and all those funtions, but what can I say more :), I've also seen your lars project, seem interesting, if I will have chancen i will try to use it :)

**Comment by joeybloggs** [comment]
Awesome @krhubert I'm currently building a website and then converting a large web app to use lars, hence the 0.7.0 version, after that having 2 sites in production I'll bump the version to 1.0... but truthfully it's stable and nothing is likely to change, just adding functionality. I will be creating a sample app as well for use in a blog post about it.

If you need any help, have questions or think it's lacking something, just let me know and I'll see what I can do.

**Pull request closed without merging**
