### PR TITLE
Add baked in validators for containsfield and excludesfield

### PR DESCRIPTION
**Pull request by fharding1**
- [x] Tests exist or have been written that cover this particular change.

Change Details:

- Adds containsfield baked in validator, as well as tests and documentation for containsfield.
- Adds excludesfield baked in validator, as well as tests and documentation for excludesfield.

@go-playground/admins

### CODE REVIEW

**Comment by fharding1** [comment]
I considered making these validators panic on non-string types but it looks like that isn't the behavior of other validators so I decided against it. I also considered adding support for `fmt.Stringer` but did not for the same reason.

**Comment by joeybloggs** [comment]
Hey @fharding1 thanks for the PR!

I just have one request, can it be renamed to `fieldcontains` and `fieldexcludes`?
I was confused by the naming, I was reading it as if it was checking that the actual field was contained in the struct rather than containing the value.

**Comment by fharding1** [comment]
@joeybloggs thanks for the feedback, done.

**Comment by fharding1** [comment]
No worries, I don't mean to be a bother, I just figured after a month you might have forgotten about it. Hope you and your family feels better soon!

**Comment by joeybloggs** [comment]
@fharding1 no worries, I do forget sometimes too ;)

**Comment by axiaoxin** [comment]
excludesfield is still on godoc https://godoc.org/github.com/go-playground/validator#hdr-Field_Excludes_Another_Field

**Comment by jtyoui** [comment]
😔excludesfield and containsfield  is still on godoc, this keeps reporting errors.
 https://godoc.org/github.com/go-playground/validator#hdr-Field_Excludes_Another_Field

**Pull request merged**
