### PR TITLE
Add hostname_port validator feature

### PR DESCRIPTION
**Pull request by terala**
Fixes Or Enhances # 562

- [x] Tests exist or have been written that cover this particular change.

Change Details:
- Add support for `hostname_port` validator. Tests added for this validator.
- Fix regex for `hostnameRegexStringRFC1123` so it will reject hostnames like `extra..com`.

@go-playground/admins

### CODE REVIEW

**Comment by terala** [comment]
@deankarn  or anyone.. can you guys take a look?

**Comment by deankarn** [comment]
Hey @terala would you be able to add documentation for the new validation [here](https://github.com/go-playground/validator/blob/master/doc.go)

**Comment by terala** [comment]
I sure can. Will update the documentation.

**Comment by terala** [comment]
@deankarn Added the documentation.

**Pull request merged**
