### PR TITLE
State / Province codes not updated as in iso3166_2 standards #1087

### PR DESCRIPTION
**Pull request by jozephp**
## Fixes Or Enhances
Updated the state / province codes as per ISO website iso3166_2 standards

**Make sure that you've checked the boxes below before you submit PR:**
- [X ] Tests exist or have been written that cover this particular change.

@go-playground/validator-maintainers

This is to cover the https://github.com/go-playground/validator/issues/1087

### CODE REVIEW

**Comment by jozephp** [comment]
@[deankarn ](https://github.com/deankarn) can you please help review this ?

**Comment by jozephp** [comment]
Could someone work to review this ?

**Comment by jozephp** [comment]
@deankarn  gentle reminder to approve and merge this PR

**Comment by deankarn** [comment]
@jozephp thanks for the reminder, will try and look at this and other PRs within the next couple weeks. Benn busy with some other open source projects the last few weeks.

**Review by deankarn — APPROVED** [review]

**Pull request merged**
