### PR TITLE
Resolving "Validating unexported fields #417"

### PR DESCRIPTION
**Pull request by nikolaianohyn**
## Add supporting for validation private fields https://github.com/go-playground/validator/issues/417

@go-playground/validator-maintainers

### CODE REVIEW

**Review by mgerasimchuk — APPROVED** [review]

**Review by deankarn — CHANGES_REQUESTED** [review]
Thanks for the PR!

I still have to review carefully, new laptop still in the mail so be a bit, but due to the use of unsafe I will request that this needs to become an opt-in option when initializing validator and documentation can indicate that and that opting in accepts that risk.

**Comment by nikolaianohyn** [comment]
@deankarn thanks for your proposal, it looks valid. Changes added.

**Comment by nikolaianohyn** [comment]
@deankarn if I can speed up the review process, let me know.

**Review by deankarn — APPROVED** [review]
LGTM

I will add a little more to the opt-in function comment but code looks great!

**Pull request merged**
