### PR TITLE
Lazily initialize regexes to speed up `init()`

### PR DESCRIPTION
**Pull request by kylecarbs**
Using `GODEBUG=inittrace=1` I found a relatively constant 10ms init caused by this function.

@go-playground/validator-maintainers

### CODE REVIEW

**Comment by deankarn** [comment]
@kylecarbs out of curiosity, what is your use case where `10ms` is not tolerable?

**Comment by kylecarbs** [comment]
@deankarn this package is imported in our CLI. Adding that overhead to every invocation (even help) isn't great.

**Comment by kylecarbs** [comment]
@deankarn any changes needed for me to push this through?

**Comment by deankarn** [comment]
@kylecarbs sorry for the lateness of my reply, been busy.

My only concern is the `sync.Mutex` overhead for longer running applications, can you change the implementation to use [sync.Once](https://pkg.go.dev/sync#Once) instead which uses lower level atomics?

**Comment by kylecarbs** [comment]
@deankarn good idea. Will change in a bit!

**Comment by deankarn** [comment]
I will check back later tonight/tomorrow :)

**Pull request closed without merging**
