### PR TITLE
Make repo a Go module

### PR DESCRIPTION
**Pull request by mastertinner**
Fixes Or Enhances

**Make sure that you've checked the boxes below before you submit PR:**
- [x] Tests exist or have been written that cover this particular change.

Change Details:

- Add a `go.mod` and a `go.sum` file that describe the dependencies and make this repo a Go module.

@go-playground/admins

### CODE REVIEW

**Comment by mastertinner** [comment]
Another discussion should be whether to move from importing from `gopkg.in` to directly importing from `github.com`.

**Comment by joeybloggs** [comment]
Hey @mastertinner thanks,

I was considering this and once go modules are on by default in the next release I was going to convert this library and probably change stop using gopkg.in; it will require a version bump as it's a breaking change, but I have a few other things that also require breaking changes.

I think the changes in this PR have already been fixed by another PR.

**Comment by wcsiu** [comment]
Can someone please add the go.mod, go.sum? It shouldn't break anything and the library will be go module ready.

**Comment by offlinehacker** [comment]
Same issue here, i guess this is the only decent validation library in go, and can't even use it without forking

**Comment by deankarn** [comment]
🤣 ok, guys, some of the comments here are quite humorous and outlandish.

Now that Go modules has been released and because this library is > v1 I now know that migrating **IS** a breaking change now that the versions affect the import paths within other programs(totally crazy).

I will start on a v10 branch when I can find some time to avoid any breaking changes and other headaches and issues that Go modules has and has brought to the table.

**Comment by deankarn** [comment]
****

**Pull request closed without merging**
