### PR TITLE
Let validators see current fields paths

### PR DESCRIPTION
**Pull request by zenovich**
Fixes Or Enhances # .

**Make sure that you've checked the boxes below before you submit PR:**
- [x] Tests exist or have been written that cover this particular change.

Change Details:

Currently there is no way for validators to know which fields they are checking. So validators depending not only on the value, but on the field itself (e.g. checking that the field is listed in some external source) cannot work.

This PR adds new methods Path() & StructPath() into the FieldLevel interface allowing validators to get a path (based on FieldName-s) or a struct path (based on StructFieldName-s) of the current field respectively.

@go-playground/admins

### CODE REVIEW

**Comment by deankarn** [comment]
Hey @zenovich can you elaborate on why having these paths is useful within the validators?

I'm concerned that the code has been moved outside of the validation check which means that this logic and allocations will now happen for every field being validated, even if there's no validation error. I'm inclined not to accept the PR unless there's a very good reason.

**Comment by zenovich** [comment]
Hi @deankarn 
The problem is that we need these paths during the validation process itself, not for errors. We decide if the field is valid basing on the paths. This means that this logic really should happen for every field being validated, otherwise we cannot even decide if there's an error or not.

**Comment by deankarn** [comment]
@zenovich could you provide a real world example of when these paths would be used? I can't think of any off the top of my head.

**Comment by zenovich** [comment]
@deankarn Consider we have a structure with data:struct{ a struct {b *string}; b *string} (it is valid for any of "b"-s to be nil). Also, we have a map filled on parsing a web-request, letting us know which of the fields are given by the user: paramsGiven = map[string]bool{"a":true, "b": true, "a.b": false}. Now imagine that we need to validate "b" & "a.b" in the same way, but only if they are given by the user (remember that nil is a valid value and we cannot consider it as "not given"). To solve this problem, we use a custom validator which searches for a field's path in "paramsGiven" before doing real checks. That's why we need to be able to get correct fields path in validators.

**Comment by deankarn** [comment]
@zenovich I'm wondering why the current functionality would not work for you.
you are able to pass external information through the [context.Context](https://github.com/go-playground/validator/blob/5b97da4cbf655ab460ec928f6737baa6edd2e74d/baked_in.go#L27) to the validation and struct validation currently and there are [built-in helpers for traversing strings by namespace/path](https://github.com/go-playground/validator/blob/fb6c45823ad5db49e788621271c6f86fa3a0f149/field_level.go#L58) just like in your example.

**Comment by zenovich** [comment]
> @zenovich I'm wondering why the current functionality would not work for you.
> you are able to pass external information through the [context.Context](https://github.com/go-playground/validator/blob/5b97da4cbf655ab460ec928f6737baa6edd2e74d/baked_in.go#L27) to the validation and struct validation currently and there are [built-in helpers for traversing strings by namespace/path](https://github.com/go-playground/validator/blob/fb6c45823ad5db49e788621271c6f86fa3a0f149/field_level.go#L58) just like in your example.

These build-in helpers were added two months after this PR, so I don't know if they can help or not.

**Comment by zenovich** [comment]
I'll check

**Comment by zenovich** [comment]
@deankarn It looks like those new build-in helpers still don't allow a validator to figure out which of the fields it is checking at the moment. And without this information a validator cannot check if the field was given by the user or not (no matter whether this information is stored in the context or somewhere else).

**Comment by deankarn** [comment]
@zenovich would [StructPartial](https://pkg.go.dev/github.com/go-playground/validator/v10#Validate.StructPartial) be what you're looking for to filter only the fields that need to be validated using the map example?

**Comment by zenovich** [comment]
@deankarn, not really. Actually the StructPartial does the opposite to what I need. I need to validate all the fields, but my custom validator should know which field it is validating at the moment.

**Comment by deankarn** [comment]
Sorry closing due to age. This is something I will think about for the next version.

**Pull request closed without merging**
